### Get All Currencies
GET http://localhost:3001/admin/currencies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJybWVuZGV6OTAwNTI5QGdtYWlsLmNvbSIsInN1YiI6NCwicm9sZXMiOlsiYWRtaW4iXSwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTc1MjA4Nzc3NiwiZXhwIjoxNzUyMDkxMzc2fQ.tGlegdy2UqDLHNPOflA0kNqqxB-robMX4V_8IwjqVLI

### Get Currency by ID
GET http://localhost:3001/admin/currencies/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJybWVuZGV6OTAwNTI5QGdtYWlsLmNvbSIsInN1YiI6NCwicm9sZXMiOlsiYWRtaW4iXSwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTc1MjA4Nzc3NiwiZXhwIjoxNzUyMDkxMzc2fQ.tGlegdy2UqDLHNPOflA0kNqqxB-robMX4V_8IwjqVLI