export enum WithdrawalStatus {
  CREATED = 'CREATED',
  AWAITING_TOPUP = 'AWAITING_TOPUP',
  AWAITING_ALLOWANCE = 'AWAITING_ALLOWANCE',
  READY_TO_WITHDRAW = 'READY_TO_WITHDRAW',
  ONCHAIN_SUBMITTED = 'ONCHAIN_SUBMITTED',
  ONCHAIN_CONFIRMED = 'ONCHAIN_CONFIRMED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}
