export function generateCode(digits: number = 6): string {
  return Math.floor(Math.random() * Math.pow(10, digits))
    .toString()
    .padStart(digits, '0');
}

// ------------------------------------------------------------
// Error codes centralizados para toda la aplicación
// ------------------------------------------------------------

export const ErrorCodes = {
  DOCUMENT_ALREADY_REGISTERED: 'DOCUMENT_ALREADY_REGISTERED',
  INVALID_CODE: 'INVALID_CODE',
  // Usuarios
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_NOT_VERIFIED: 'USER_NOT_VERIFIED',
  USER_INVALID_STATUS: 'USER_INVALID_STATUS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS: 'PHONE_ALREADY_EXISTS',
  FAILED_TO_SEND_VERIFICATION_EMAIL: 'FAILED_TO_SEND_VERIFICATION_EMAIL',
  SECOND_FACTOR_ALREADY_ENABLED: 'SECOND_FACTOR_ALREADY_ENABLED',
  SECOND_FACTOR_NOT_ENABLED: 'SECOND_FACTOR_NOT_ENABLED',
  CANNOT_DEACTIVATE_WITH_2FA_ENABLED: 'CANNOT_DEACTIVATE_WITH_2FA_ENABLED',
  TRANSFERS_ALREADY_UNLOCKED: 'TRANSFERS_ALREADY_UNLOCKED',
  TRANSFERS_ALREADY_LOCKED: 'TRANSFERS_ALREADY_LOCKED',
  CANNOT_UNLOCK_WITH_REJECTED_COMPLIANCE:
    'CANNOT_UNLOCK_WITH_REJECTED_COMPLIANCE',

  // Autenticación
  INVALID_TOKEN: 'INVALID_TOKEN',
  EXPIRED_TOKEN: 'EXPIRED_TOKEN',
  TOKEN_ALREADY_USED: 'TOKEN_ALREADY_USED',
  NO_TOKEN_PROVIDED: 'NO_TOKEN_PROVIDED',
  INVALID_TOKEN_TYPE: 'INVALID_TOKEN_TYPE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  RESOURCE_ACCESS_DENIED: 'RESOURCE_ACCESS_DENIED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  USER_BLOCKED: 'USER_BLOCKED',

  // Wallets
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  WALLET_ALREADY_EXISTS: 'WALLET_ALREADY_EXISTS',
  WALLET_INSUFFICIENT_BALANCE: 'WALLET_INSUFFICIENT_BALANCE',
  WALLET_INVALID_ADDRESS: 'WALLET_INVALID_ADDRESS',

  // Transacciones
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
  TRANSACTION_PENDING: 'TRANSACTION_PENDING',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  AMOUNT_BELOW_MINIMUM: 'AMOUNT_BELOW_MINIMUM',
  LIMIT_EXCEEDED: 'LIMIT_EXCEEDED',

  // KYC
  KYC_NOT_FOUND: 'KYC_NOT_FOUND',
  KYC_INVALID_STATUS: 'KYC_INVALID_STATUS',
  KYC_ALREADY_SUBMITTED: 'KYC_ALREADY_SUBMITTED',
  KYC_UNDER_REVIEW: 'KYC_UNDER_REVIEW',
  KYC_REJECTED: 'KYC_REJECTED',
  KYC_DOCUMENT_EXPIRED: 'KYC_DOCUMENT_EXPIRED',
  KYC_INVALID_TYPE: 'KYC_INVALID_TYPE',
  KYC_DOCUMENT_NOT_FOUND: 'KYC_DOCUMENT_NOT_FOUND',
  KYC_DOCUMENT_INVALID_STATUS: 'KYC_DOCUMENT_INVALID_STATUS',
  KYC_NO_DOCUMENTS_TO_REJECT: 'KYC_NO_DOCUMENTS_TO_REJECT',

  // Monedas
  CURRENCY_NOT_FOUND: 'CURRENCY_NOT_FOUND',
  CURRENCY_NOT_ACTIVE: 'CURRENCY_NOT_ACTIVE',
  CURRENCY_PRICE_NOT_FOUND: 'CURRENCY_PRICE_NOT_FOUND',

  // Tarifas (Fees)
  FEE_NOT_FOUND: 'FEE_NOT_FOUND',
  FEE_ALREADY_EXISTS: 'FEE_ALREADY_EXISTS',

  // Límites
  LIMIT_NOT_FOUND: 'LIMIT_NOT_FOUND',
  LIMIT_ALREADY_EXISTS: 'LIMIT_ALREADY_EXISTS',

  // Servidor
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  ENVIRONMENT_VARIABLE_ERROR: 'ENVIRONMENT_VARIABLE_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',

  // Firebase App Check
  FIREBASE_APP_CHECK_TOKEN_MISSING: 'FIREBASE_APP_CHECK_TOKEN_MISSING',
  FIREBASE_APP_CHECK_TOKEN_INVALID: 'FIREBASE_APP_CHECK_TOKEN_INVALID',
  FIREBASE_APP_CHECK_TOKEN_EXPIRED: 'FIREBASE_APP_CHECK_TOKEN_EXPIRED',
  FIREBASE_APP_CHECK_VERIFICATION_FAILED:
    'FIREBASE_APP_CHECK_VERIFICATION_FAILED',
  FIREBASE_APP_CHECK_APP_ID_MISMATCH: 'FIREBASE_APP_CHECK_APP_ID_MISMATCH',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
