export enum UserSecurityActionType {
  ACCOUNT_LOCK = 'ACCOUNT_LOCK',
  ACCOUNT_UNLOCK = 'ACCOUNT_UNLOCK',
  TRANSFER_LOCK = 'TRANSFER_LOCK',
  TRANSFER_UNLOCK = 'TRANSFER_UNLOCK',
  COMPLIANCE_APPROVED = 'COMPLIANCE_APPROVED',
  COMPLIANCE_REJECTED = 'COMPLIANCE_REJECTED',
  ADMIN_USER_CREATED = 'ADMIN_USER_CREATED',
  ADMIN_USER_UPDATED = 'ADMIN_USER_UPDATED',
  ADMIN_USER_ACTIVATED = 'ADMIN_USER_ACTIVATED',
  ADMIN_USER_DEACTIVATED = 'ADMIN_USER_DEACTIVATED',
  VERIFICATION_EMAIL_RESENT = 'VERIFICATION_EMAIL_RESENT',
}
